name: Detect JSON Changes

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  detect-json-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Detect JSON Changes
        run: |
          ls
          git branch
          latest_commit_sha=$(git rev-parse origin/main)
          echo "Latest commit from main branch : $latest_commit"
          changed_files=$(git diff --name-only $latest_commit_sha)
          git --no-pager diff $latest_commit_sha -- $changed_files   | grep '^+' | awk '{$1=""; print $0}'
          TEST=$(git --no-pager diff $latest_commit_sha -- $changed_files   | grep '^+' | awk '{$1=""; print $0}')
          gh api \
          --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments \
            -f body="hello @dinhdobathi1992 - Here are some changed:  \n --  \n```$TEST```" \
           -f path='file1.txt' \
           -F start_line=1 \
           -f start_side='RIGHT' \
           -F line=2 \
           -f side='RIGHT'
          # for file in $changed_files; do
          #   if [[ $file == *.json ]]; then
          #     echo "Changes in $file:"
          #     git --no-pager diff $latest_commit_sha -- $file   | grep '^+' | awk '{$1=""; print $0}'
          #   fi
          # done
