name: Detect JSON Changes

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  detect-json-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Detect JSON Changes
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          ls
          git branch
          latest_commit_sha=$(git rev-parse origin/main)
          echo "Latest commit from main branch : $latest_commit"
          changed_files=$(git diff --name-only $latest_commit_sha)
          git --no-pager diff $latest_commit_sha -- $changed_files   | grep '^+' | awk '{$1=""; print $0}'
          TEST=$(git --no-pager diff $latest_commit_sha -- $changed_files   | grep '^+' | awk '{$1=""; print $0}')
          gh api \
          --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments \
            -f body="hello @dinhdobathi1992 - Here are some changed: |
              \`\`\`
              --  $TEST
              \`\`\`"
