on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        type: string
        required: true
        description: url for n8n
jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api octocat
          COMMENT="The review count is ${{ env.REVIEW_COUNT }} - You are good to go"
          gh api \
          --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dinhdobathi1992/test-status/issues/19/comments \
            -f body='"${COMMENT}"' \
           -f path='file1.txt' \
           -F start_line=1 \
           -f start_side='RIGHT' \
           -F line=2 \
           -f side='RIGHT' 
          ###
          echo ${{ github.event.inputs.resumeUrl }} 
      - name: Resume n8n Workflow
        run: |
          echo "RUN_ID=$GITHUB_RUN_ID"
          curl -X POST "${{ inputs.resumeUrl }}" \
               -H "Content-Type: application/json" \
               -d '{"status": "resumed by GitHub", "run_id": "'"${{ github.run_id }}"'"}'


