name: Get Number of Approvals

on:
  pull_request_review:
    types:
      - submitted


jobs:
  get-approvals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Git credentials
      run: |
        git config --global user.name "Robot"
        git config --global user.email "dinhdobathi@gmail.com"
        
    - name: Check for file changes
      id: file_changed
      run: |
        base_branch="main"  # Replace with the base branch name
        changed_files=$(git diff --name-only origin/main HEAD )

        echo "Changed files:"
        echo "$changed_files"

        echo "::set-output name=changed_files::$changed_files"
        
    - name: Notify if specific file changed
      id: check_changes
      if: ${{ contains(steps.file_changed.outputs.changed_files, 'prod') }}
      run: |
        echo "File 'prod' has changed."
        echo "::set-output name=changed::true"
        echo "changed=true" >> $GITHUB_OUTPUT

    - name: Get pull request information
      id: get_pr_info
      if: ${{ contains(steps.file_changed.outputs.changed_files, 'prod') }}
      run: |
          REVIEWS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }} " -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews | jq 'map(select(.state == "COMMENTED")) | length')
          
          #REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.ROBOT_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews"  | jq '. | select(.state == "COMMENTED") | length' )
          echo "Number of reviews: $REVIEWS"
          echo "REVIEW_COUNT=$REVIEWS" >> $GITHUB_ENV
    - name: Use the review count
      run: echo "The review count is ${{ env.REVIEW_COUNT }}"

    # - name: Add Comment
    #   run: |
    #       COMMENT="The review count is ${{ env.REVIEW_COUNT }}"
        
    #       curl -X POST \
    #         -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         "https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments" \
    #         -d '{"body":"'"${COMMENT}"'"}'

    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Use the token
      if: ${{ contains(steps.file_changed.outputs.changed_files, 'prod') }}
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api octocat
        gh api \
        --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments \
          -f body='Great stuff!' \
         -f path='file1.txt' \
         -F start_line=1 \
         -f start_side='RIGHT' \
         -F line=2 \
         -f side='RIGHT' 


    - name: Conditional Self-Fail
      if: ${{ contains(steps.file_changed.outputs.changed_files, 'prod') }}
      run: |
        if [ $REVIEW_COUNT -lt 2 ]; then
          echo "Insufficient reviews. Failing workflow. You need at least 2 approvers for prod's changes"
          COMMENT="The review count is ${{ env.REVIEW_COUNT }} - You need at least 2 approvers for prod's changes"
        
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ROBOT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments" \
            -d '{"body":"'"${COMMENT}"'"}'
          exit 1
        else
          echo "Sufficient reviews. Continuing with workflow."
          COMMENT="The review count is ${{ env.REVIEW_COUNT }} - You are good to go"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ROBOT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments" \
            -d '{"body":"'"${COMMENT}"'"}'
        fi
