name: sample-workflow

# Run on all pull_request related events
on:
  pull_request:

permissions:
  contents: read # this is necessary for the Action to be able to read the contents of the repo

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to checkout all branches for this Action to work

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.4.0
        id: git-diff-action
            
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"

      # Print the diff in JSON format
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: |
          cat $DIFF
          test=$(cat $DIFF)
          echo $test
          jq '{files: [.files[] | {path, changes: [.chunks[].changes[] | {type, lineAfter, content: .content | rtrimstr("\r")}]}]}' $DIFF
          
      # Print the diff in raw git format
      - name: print raw diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        run: |
          cat $DIFF
          test=$(cat $DIFF)
          echo $test
          COMMENT2=$test
          echo $COMMENT2
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

    
      - name: Sent RAW 
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        run: |
          gh api octocat
          COMMENT="The review count is ${{ env.REVIEW_COUNT }} - You are good to go"
          TEST="$(cat $DIFF)"
          echo $TEST
          gh api \
          --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments \
            -f body="$TEST" \
           -f path='file1.txt' \
           -F start_line=1 \
           -f start_side='RIGHT' \
           -F line=2 \
           -f side='RIGHT' 

           
      - name: Sent JSON 
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: |
          gh api octocat
          COMMENT="The review count is ${{ env.REVIEW_COUNT }} - You are good to go"
          jq '{files: [.files[] | {path, changes: [.chunks[].changes[] | {type, lineAfter, content: .content | rtrimstr("\r")}]}]}' $DIFF)
          TEST="$(jq '{files: [.files[] | {path, changes: [.chunks[].changes[] | {type, lineAfter, content: .content | rtrimstr("\r")}]}]}' $DIFF)"
          echo $TEST
          gh api \
          --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dinhdobathi1992/test-status/issues/${{ github.event.pull_request.number }}/comments \
            -f body="$TEST" \
           -f side='RIGHT' 
           
      # - name: Set the value in bash
      #   id: step_one
      #   env:
      #     GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      #     DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
      #   run: |
      #     {
      #       echo 'RAW_RESPONSE<<EOF'
      #       cat $DIFF
      #       echo EOF
      #     } >> "$GITHUB_ENV"
      # - name: Read file content
      #   env:
      #     GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      #     DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
      #   id: read-file
      #   run: |
      #     echo $(cat $DIFF)
      #     echo "::set-output name=content::$(cat $DIFF)"
      #     echo ${{ env.RAW_RESPONSE }}
