on:
  workflow_dispatch:
jobs:
  get-env-output:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: list file changed
        id: list_file_changed
        shell: bash
        run: |
          
          file="aws/EXAMPLE/be-env-cfg.dcbencrypted"
          client_name=$(dirname "$file" | awk -F/ '{print $NF}')
          echo $client_name
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
          ls -ls aws/example
          echo "::set-output name=env::$client_name"

      - name: Run tests
        uses: mathiasvr/command-output@v1
        id: tests
        env:
            TEST: ${{ vars.AWS_ACCESS_KEY_ID_EXAMPLE }}
            ENV: ${{ steps.list_file_changed.outputs.env }}
            SELECTED_COLOR: ${{ steps.list_file_changed.outputs.SELECTED_COLOR }}
            AWS_ACCESS_KEY_ID: ${{ vars[format('AWS_ACCESS_KEY_ID_{0}', env.ENV)] }}
            AWS_SECRET_ACCESS_KEY_EXAMPLE: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', env.ENV)] }}
        with:
          run: |
              echo $TEST
              echo $AWS_ACCESS_KEY_ID
              echo $ENV
              echo $SELECTED_COLOR
              echo $AWS_ACCESS_KEY_ID_EXAMPLE
              echo $AWS_SECRET_ACCESS_KEY_EXAMPLE
                
