on:
  workflow_dispatch:
jobs:
  get-env-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: list file changed
        shell: bash
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          file="aws/example/be-env-cfg.dcbencrypted"
          client_name=$(dirname "$file" | awk -F/ '{print $NF}')
          ls -ls aws/example
          echo "::set-output name=env::$$(dirname "$file" | awk -F/ '{print $NF}')"

      - name: Run tests
        uses: mathiasvr/command-output@v1
        id: tests
        env:
            ENV: ${{ steps.list-file-changed.outputs.env }}
        with:
          run: |
              echo $ENV
      
                
