name: Get Number of Approvals

on:
  pull_request_review:
    types:
      - submitted

jobs:
  get-approvals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"

    - name: Get pull request information
      id: get_pr_info
      run: |
          REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews" | jq length )
          echo "Number of reviews: $REVIEWS"
    - name: Set output variable
      id: set_output
      run: echo "REVIEW_COUNT=$REVIEWS" >> $GITHUB_ENV

    - name: Use the review count
      run: echo "The review count is ${{ env.REVIEW_COUNT }}"
