on:
  workflow_dispatch:
jobs:
  get-env-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Generate a tokene
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: list file changed
        id: list_file_changed
        shell: bash
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          file="aws/example/be-env-cfg.dcbencrypted"
          client_name=$(dirname "$file" | awk -F/ '{print $NF}')
          echo $client_name
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
          ls -ls aws/example
          echo "::set-output name=env::$client_name"

      - name: Run tests
        uses: mathiasvr/command-output@v1
        id: tests
        env:
            ENV: ${{ steps.list_file_changed.outputs.env }}
            SELECTED_COLOR: ${{ steps.list_file_changed.outputs.SELECTED_COLOR }}
        with:
          run: |
              echo $ENV
              echo $SELECTED_COLOR
      
                
